apiVersion: v1
type: postrenderer/v1
name: helm-kustomize
version: 0.1.0
description: A Helm post-renderer plugin that applies Kustomize transformations
runtime: subprocess
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/helm-kustomize-plugin
